name: PyPI Pipeline

on:
  push:

jobs:
  Pre-Commit:
    uses: ./.github/workflows/01-pre-commit.yaml

  CI:
    uses: ./.github/workflows/02-ci.yaml
    secrets: inherit

  Build-and-Release-to-Pypi:
    needs:
      - CI
      - Pre-Commit
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/03-build-and-publish-to-pypi.yaml
    secrets: inherit
