name: Build-and-Publish-to-PyPI

on:
  workflow_call:

jobs:
  Merge:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.12' ]

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git identity
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Merge into master
        id: merge
        run: |
          git checkout master
          git merge --no-ff $GITHUB_REF
        continue-on-error: false

      - name: Push to master
        if: steps.merge.outcome == 'success'
        run: |
          git push origin master
        env:
          GH_TOKEN: ${{ secrets.GH_REPO_ACCESS_BY_OWN_APPS }}

      - name: Debug Environment
        run: env

  Build-and-Publish:
    needs: Merge
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write
      id-token: write

    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.12' ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry & Dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build package
        run: |
          poetry build
          ls -la dist  # Just to verify the artifacts exist

      - name: New release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ vars.GITHUB_HEAD_REF }}
          name: ${{ vars.GITHUB_HEAD_REF }}
          body_path: ${{ github.workspace }}/ReleaseNotes.md
          draft: false
          prerelease: false

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}  # or your PyPI API token
          packages_dir: dist
          verify_metadata: true  # optional, default: true
          # skip_existing: false   # optional
          # attestations: true     # optional

  Send-Notice:
    needs: Build-and-Publish
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.12' ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Send release email notification
        uses: betterfor/action-send-mail@main
        with:
          server_address: mail.realtimeevents.co
          server_port: 465
          username: ${{ secrets.RELEASE_EMAIL_USER }}
          password: ${{ secrets.RELEASE_EMAIL_PASSWORD }}
          subject: 'New Release: ${{ github.repository }} ${{ github.ref_name }}'
          to: rte-development@brightedge.co.za
          from: Development Messenger
          html_body: |
            <table style="font-family: verdana;font-size:90%; border-collapse:collapse; border-style: double; border-color: 000000; border-width: 3px">
            <colgroup>
              <col style="text-align:right">
              <col style="text-align:left">
            </colgroup>
            <tr>
              <th style="text-align: center; border-bottom-style: double; border-right-style: double; border-right-width: 1px; border-bottom-width: 3px">Description</th>
              <th style="text-align: center; border-bottom-style: double; border-left-style: double; border-bottom-width: 3px; border-left-width: 1px">Detail</th>
            </tr>
            <tr>
              <td style="text-align: right; border-right-style: solid; border-bottom-style: dotted; border-right-width: 1px;border-bottom-width: 1px">Repository:</td>
              <td style="text-align: left; border-bottom-style: dotted; border-left-style: solid; border-left-width: 1px;border-bottom-width: 1px">${{ github.repository }}</td>
            </tr>
            <tr>
              <td style="text-align: right; border-right-style: solid; border-bottom-style: dotted; border-right-width: 1px;border-bottom-width: 1px">Release:</td>
              <td style="text-align: left; border-bottom-style: dotted; border-left-style: solid; border-left-width: 1px;border-bottom-width: 1px">${{ github.ref_name }}</td>
            </tr>
            <tr>
              <td style="text-align: right; border-right-style: solid; border-bottom-style: dotted; border-right-width: 1px;border-bottom-width: 1px">Actor:</td>
              <td style="text-align: left; border-bottom-style: dotted; border-left-style: solid; border-left-width: 1px;border-bottom-width: 1px">${{ github.actor }}</td>
            </tr>
            <tr>
              <td style="text-align: right; border-right-style: solid; border-bottom-style: dotted; border-right-width: 1px;border-bottom-width: 1px">Workflow:</td>
              <td style="text-align: left; border-bottom-style: dotted; border-left-style: solid; border-left-width: 1px;border-bottom-width: 1px">${{ github.workflow }}</td>
            </tr>
            <tr>
              <td style="text-align: right; border-right-style: solid; border-right-width: 1px">Release URL:</td>
              <td style="text-align: left; border-left-style: solid; border-left-width: 1px"><a href="https://github.com/${{ github.repository }}/releases/tag/${{github.ref_name}}">Click here</a></td>
            </tr>
            </table><br>'
          # cc: a@example.com,b@example.com
          # bcc: c@example.com,d@example.com
          # Optional recipient of the email response
          # reply_to: luke@example.com
          # Optional Message ID this message is replying to
          # in_reply_to: <random-luke@example.com>
          # Optional converting Markdown to HTML (set content_type to text/html too)
          # convert_markdown: true
          # Optional attachments
          # attachments: README.md
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: normal
